In [1]:
#importing library file
import pandas as pd

In [2]:
#Providing input sheet to dataset
dataset=pd.read_csv("50_Startups.csv")

In [3]:
#viewing data saved in dataset variable
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
#here we are doing one hot encoding as state is nominal data.get_dummies function work is to .saving the dataset with the updated values for nomail data in 0s and 1s format
#as we use one hot encoding we have column expansion. so there will be increase in columns.the name for column will be like initial column name with the nomial valu
#according to machine learning we have dummies in one hot encoding.so we have to delete one column to reduce memory and to avoid dummies
#so when we give drop_first=true then first column will be dropped which means it is deleted. by default it is false.
dataset=pd.get_dummies(dataset,dtype = int,drop_first=True)

In [5]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [6]:
# to get column names saved under dataset variable
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
#input variable assigning values
Independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 
       'State_Florida', 'State_New York']]

In [8]:
#checking saved values
Independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [9]:
#assinging ouput column
Dependent=dataset[['Profit']]

In [10]:
#checking data saved in the variable
Dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [16]:
#step 2: to seprate test set and trail set for this we need new library file(sklearn).here importing only needed function
#so within library file we are using only needed class and function- to reduce memory. if we import all library file from sklearn the memory will be huge

from sklearn.model_selection import train_test_split

In [12]:
#we are seeing what is there in this function. here we are passing paramter as this is parameterised function
#choosing test size as 30% so that trail data will be more and test data will be less.
train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

[    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
 7   130298.13       145530.06        323876.68              1               0
 14  119943.24       156547.42        256512.92              1               0
 45    1000.23       124153.04          1903.93              0               1
 48     542.05        51743.15             0.00              0               1
 29   65605.48       153032.06        107138.38              0               1
 15  114523.61       122616.84        261776.23              0               1
 30   61994.48       115641.28         91131.24              1               0
 32   63408.86       129219.61         46085.25              0               0
 16   78013.11       121597.55        264346.06              0               0
 42   23640.93        96189.63        148001.11              0               0
 20   76253.86       113867.30        298664.47              0               0
 43   15505.73       127382.30         35534.17              0               1
 8   120542.52       148718.95        311613.29              0               1
 13   91992.39       135495.07        252664.93              0               0
 25   64664.71       139553.16        137962.62              0               0
 5   131876.90        99814.71        362861.36              0               1
 17   94657.16       145077.58        282574.31              0               1
 40   28754.33       118546.05        172795.67              0               0
 49       0.00       116983.80         45173.06              0               0
 1   162597.70       151377.59        443898.53              0               0
 12   93863.75       127320.38        249839.44              1               0
 37   44069.95        51283.14        197029.42              0               0
 24   77044.01        99281.34        140574.81              0               1
 6   134615.46       147198.87        127716.82              0               0
 23   67532.53       105751.03        304768.73              1               0
 36   28663.76       127056.21        201126.82              1               0
 21   78389.47       153773.43        299737.29              0               1
 19   86419.70       153514.11             0.00              0               1
 9   123334.88       108679.17        304981.62              0               0
 39   38558.51        82982.09        174999.30              0               0
 46    1315.46       115816.21        297114.46              1               0
 3   144372.41       118671.85        383199.62              0               1
 0   165349.20       136897.80        471784.10              0               1
 47       0.00       135426.92             0.00              0               0
 44   22177.74       154806.14         28334.72              0               0,
     R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
 28   66051.52       182645.56        118148.20              1               0
 11  100671.96        91790.61        249744.55              0               0
 10  101913.08       110594.11        229160.95              1               0
 41   27892.92        84710.77        164470.71              1               0
 2   153441.51       101145.55        407934.54              1               0
 27   72107.60       127864.55        353183.81              0               1
 38   20229.59        65947.93        185265.10              0               1
 31   61136.38       152701.92         88218.23              0               1
 22   73994.56       122782.75        303319.26              1               0
 4   142107.34        91391.77        366168.42              1               0
 33   55493.95       103057.49        214634.81              1               0
 35   46014.02        85047.44        205517.64              0               1
 26   75328.87       144135.98        134050.07              1               0
 34   46426.07       157693.92        210797.67              0               0
 18   91749.16       114175.79        294919.57              1               0,
        Profit
 7   155752.60
 14  132602.65
 45   64926.08
 48   35673.41
 29  101004.64
 15  129917.04
 30   99937.59
 32   97427.84
 16  126992.93
 42   71498.49
 20  118474.03
 43   69758.98
 8   152211.77
 13  134307.35
 25  107404.34
 5   156991.12
 17  125370.37
 40   78239.91
 49   14681.40
 1   191792.06
 12  141585.52
 37   89949.14
 24  108552.04
 6   156122.51
 23  108733.99
 36   90708.19
 21  111313.02
 19  122776.86
 9   149759.96
 39   81005.76
 46   49490.75
 3   182901.99
 0   192261.83
 47   42559.73
 44   65200.33,
        Profit
 28  103282.38
 11  144259.40
 10  146121.95
 41   77798.83
 2   191050.39
 27  105008.31
 38   81229.06
 31   97483.56
 22  110352.25
 4   166187.94
 33   96778.92
 35   96479.51
 26  105733.54
 34   96712.80
 18  124266.90]

In [13]:
#based on the output we received here we can see 4 varibles is used here.so we are using varibale to assign this output
# so we are going to use 4 varibales x_train,x_test,y_train,y_test. ouputare seprated by commans. so here we have 4 set of data saved
X_train,X_test,Y_train,Y_test=train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [14]:
#checking one variable to check what data is saved
X_train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
7   130298.13       145530.06        323876.68              1               0
14  119943.24       156547.42        256512.92              1               0
45    1000.23       124153.04          1903.93              0               1
48     542.05        51743.15             0.00              0               1
29   65605.48       153032.06        107138.38              0               1
15  114523.61       122616.84        261776.23              0               1
30   61994.48       115641.28         91131.24              1               0
32   63408.86       129219.61         46085.25              0               0
16   78013.11       121597.55        264346.06              0               0
42   23640.93        96189.63        148001.11              0               0
20   76253.86       113867.30        298664.47              0               0
43   15505.73       127382.30         35534.17              0               1
8   120542.52       148718.95        311613.29              0               1
13   91992.39       135495.07        252664.93              0               0
25   64664.71       139553.16        137962.62              0               0
5   131876.90        99814.71        362861.36              0               1
17   94657.16       145077.58        282574.31              0               1
40   28754.33       118546.05        172795.67              0               0
49       0.00       116983.80         45173.06              0               0
1   162597.70       151377.59        443898.53              0               0
12   93863.75       127320.38        249839.44              1               0
37   44069.95        51283.14        197029.42              0               0
24   77044.01        99281.34        140574.81              0               1
6   134615.46       147198.87        127716.82              0               0
23   67532.53       105751.03        304768.73              1               0
36   28663.76       127056.21        201126.82              1               0
21   78389.47       153773.43        299737.29              0               1
19   86419.70       153514.11             0.00              0               1
9   123334.88       108679.17        304981.62              0               0
39   38558.51        82982.09        174999.30              0               0
46    1315.46       115816.21        297114.46              1               0
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
47       0.00       135426.92             0.00              0               0
44   22177.74       154806.14         28334.72              0               0

In [17]:
#standarisation. 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [18]:
#now we are going to create model. we identified as  support vector model. for that under sklearn library we are going to use model creation class and linear Regression under svm function
from sklearn.svm import SVR

In [19]:
#creating the variable as regressor best practise is to use the varibale like this and assiging a class to this variable
#SVM used for non linear data. under this we have 2 category as linear data(line coverage with datset near points) and non linear data(hyperbola).
#here we are using linear one-tried with 
regressor=SVR(kernel="linear")

In [20]:
#now we are going to call a fit function from this class and providing input via parameter. this is learning phase where this model leanr the input which is the training set
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='linear')

In [21]:
regressor.n_support_

array([34], dtype=int32)

In [22]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [23]:
#evaluation metrics. if values is nearly 1 then model created is fine if nearly 0 then model is not good
#so we are going to find the predicted value for the test data. x test is the input value and y test is the output value
y_pred=regressor.predict(X_test)

In [24]:
#to calculate the r_score we need y test value and y predicted value.so with that score is calculated
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [25]:
# as value is nearly 1 this is good model. before saving we should check the performance of the model
r_score

-0.05569157045504447

In [26]:
#trying same with rbf pattern- this is default pattern system will take if no input provided
regressor=SVR(kernel="rbf")
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [27]:
regressor.n_support_

array([34], dtype=int32)

In [28]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [29]:
regressor.intercept_

array([108734.04106363])

In [30]:
y_pred=regressor.predict(X_test)

In [31]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

-0.057418393916219834

In [32]:
#trying same with poly pattern- this is default pattern system will take if no input provided
regressor=SVR(kernel="poly")
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='poly')

In [33]:
regressor.n_support_

array([34], dtype=int32)

In [34]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [35]:
regressor.intercept_

array([108734.51317851])

In [36]:
y_pred=regressor.predict(X_test)

In [37]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

-0.05710387514922144

In [38]:
#trying same with sigmoid pattern- this is default pattern system will take if no input provided
regressor=SVR(kernel="sigmoid")
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='sigmoid')

In [39]:
regressor.n_support_

array([34], dtype=int32)

In [40]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [41]:
regressor.intercept_

array([108733.63125694])

In [42]:
y_pred=regressor.predict(X_test)

In [43]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

-0.057209358534722865

In [44]:
#trying same with rbf pattern- this is default pattern system will take if no input provided
#c as 100
regressor=SVR(kernel="rbf",C=100.0)
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100.0)

In [45]:
regressor.n_support_

array([34], dtype=int32)

In [46]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [47]:
regressor.intercept_

array([108739.09636298])

In [48]:
y_pred=regressor.predict(X_test)

In [49]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

-0.05072602278128757

In [50]:
#trying same with linear pattern- this is default pattern system will take if no input provided
regressor=SVR(kernel="linear",C=100.0)
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100.0, kernel='linear')

In [51]:
regressor.n_support_

array([35], dtype=int32)

In [52]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34], dtype=int32)

In [53]:
regressor.intercept_

array([108725.91709349])

In [54]:
y_pred=regressor.predict(X_test)

In [55]:

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

0.10646819600577384

In [56]:
#trying same with poly pattern- this is default pattern system will take if no input provided
regressor=SVR(kernel="poly",C=100.0)
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100.0, kernel='poly')

In [57]:
regressor.n_support_

array([34], dtype=int32)

In [58]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [59]:
regressor.intercept_

array([108786.30785111])

In [60]:
y_pred=regressor.predict(X_test)

In [61]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

-0.019802139315272305

In [62]:
#trying same with sigmoid pattern- this is default pattern system will take if no input provided
regressor=SVR(kernel="sigmoid",C=100.0)
regressor.fit(X_train,Y_train)

C:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100.0, kernel='sigmoid')

In [63]:
regressor.n_support_

array([35], dtype=int32)

In [64]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34], dtype=int32)

In [65]:
regressor.intercept_

array([108735.4816565])

In [66]:
y_pred=regressor.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

-0.03045351486430925